-- =============================================================================
-- Portfolio database — full schema dump
-- Project: portfolio (tmdeznfqdcyarrnixday) — Supabase / Postgres 17
-- Generated: 2026-08-28
-- =============================================================================
-- WARNING: The RLS policies below (auth_codes, users, experiences, skills,
-- projects, education, courses) use USING (true) / WITH CHECK (true) for the
-- `public` role. This means any client holding the anon key can read, insert,
-- update, or delete ANY row in these tables. `project_categories` has RLS
-- disabled entirely. This dump reproduces the schema exactly as it currently
-- exists — review the policies section before applying this to a new project.
-- =============================================================================

BEGIN;

-- =============================================================================
-- EXTENSIONS
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto"   WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"  WITH SCHEMA extensions;

-- =============================================================================
-- TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE public.users (
    id                        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      character varying(255) NOT NULL,
    job_title                 character varying(255),
    email                     character varying(255) NOT NULL,
    hero_description          text,
    about_description         text,
    capabilities_description  text,
    about_title               character varying(500),
    linkedin_url              character varying(500),
    github_url                character varying(500),
    resume_url                character varying(500),
    picture_url               character varying(500),
    portfolio_name            character varying(255),
    is_active                 boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_portfolioname_key UNIQUE (portfolio_name)
);

-- -----------------------------------------------------------------------------
-- project_categories
-- -----------------------------------------------------------------------------
CREATE TABLE public.project_categories (
    id         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    integer,
    name       character varying(100) NOT NULL,
    sort_order integer DEFAULT 0,
    CONSTRAINT project_categories_pkey PRIMARY KEY (id),
    CONSTRAINT unique_category_per_user UNIQUE (name, user_id),
    CONSTRAINT project_categories_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- experiences
-- -----------------------------------------------------------------------------
CREATE TABLE public.experiences (
    id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     integer,
    role        character varying(255),
    period      character varying(100),
    description text,
    company     character varying(255),
    CONSTRAINT experiences_pkey PRIMARY KEY (id),
    CONSTRAINT experiences_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- skills
-- -----------------------------------------------------------------------------
CREATE TABLE public.skills (
    id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer,
    name    character varying(100),
    type    character varying(10),
    CONSTRAINT skills_pkey PRIMARY KEY (id),
    CONSTRAINT unique_name UNIQUE (name, user_id),
    CONSTRAINT check_type CHECK (
        (type)::text = ANY (ARRAY['primary'::character varying, 'secondary'::character varying]::text[])
    ),
    CONSTRAINT skills_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- projects
-- -----------------------------------------------------------------------------
CREATE TABLE public.projects (
    id            integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       integer,
    title         character varying(255),
    client        character varying(255),
    role          character varying(255),
    year          integer,
    status        character varying(100),
    sort_order    integer,
    description   text,
    github_url    character varying(500),
    technologies  character varying(255),
    images        text[],
    live_url      text,
    category_id   integer,
    CONSTRAINT projects_pkey PRIMARY KEY (id),
    CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT projects_category_id_fkey FOREIGN KEY (category_id)
        REFERENCES public.project_categories(id) ON DELETE SET NULL
);

-- -----------------------------------------------------------------------------
-- education
-- -----------------------------------------------------------------------------
CREATE TABLE public.education (
    id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     integer,
    institution character varying(255) NOT NULL,
    degree      character varying(255),
    period      character varying(255),
    grade       character varying(255),
    location    character varying(255),
    description text,
    sort_order  integer DEFAULT 0,
    CONSTRAINT education_pkey PRIMARY KEY (id),
    CONSTRAINT education_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- courses
-- -----------------------------------------------------------------------------
CREATE TABLE public.courses (
    id              integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         integer,
    title           character varying(255) NOT NULL,
    provider        character varying(255),
    credential_id   character varying(255),
    certificate_url text,
    description     text,
    sort_order      integer DEFAULT 0,
    year            integer,
    type            character varying(20),
    hours           integer,
    CONSTRAINT courses_pkey PRIMARY KEY (id),
    CONSTRAINT courses_type_check CHECK (
        (type)::text = ANY (ARRAY['course'::character varying, 'certificate'::character varying]::text[])
    ),
    CONSTRAINT courses_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- auth_codes  (sequence/PK still carry the table's original name, secret_key)
-- -----------------------------------------------------------------------------
CREATE SEQUENCE public.secret_key_id_seq;

CREATE TABLE public.auth_codes (
    id         integer NOT NULL DEFAULT nextval('public.secret_key_id_seq'::regclass),
    code_hash  character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone DEFAULT (now() + '00:10:00'::interval),
    CONSTRAINT secret_key_pkey PRIMARY KEY (id)
);

ALTER SEQUENCE public.secret_key_id_seq OWNED BY public.auth_codes.id;

-- =============================================================================
-- INDEXES  (in addition to the ones backing PK / UNIQUE constraints above)
-- =============================================================================

CREATE INDEX idx_auth_codes_expires_at        ON public.auth_codes  USING btree (expires_at);
CREATE INDEX idx_auth_codes_hash              ON public.auth_codes  USING btree (code_hash);

CREATE INDEX idx_courses_user_id              ON public.courses     USING btree (user_id);
CREATE INDEX idx_courses_user_sort            ON public.courses     USING btree (user_id, sort_order);
CREATE INDEX idx_courses_user_type            ON public.courses     USING btree (user_id, type);

CREATE INDEX idx_education_user_id            ON public.education   USING btree (user_id);
CREATE INDEX idx_education_user_sort          ON public.education   USING btree (user_id, sort_order);

CREATE INDEX idx_experiences_user_id          ON public.experiences USING btree (user_id);

CREATE INDEX idx_project_categories_user_id   ON public.project_categories USING btree (user_id);

CREATE INDEX idx_projects_active              ON public.projects    USING btree (user_id, sort_order) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_projects_status              ON public.projects    USING btree (status);
CREATE INDEX idx_projects_user_id             ON public.projects    USING btree (user_id);
CREATE INDEX idx_projects_user_status_sort    ON public.projects    USING btree (user_id, status, sort_order);

CREATE INDEX idx_skills_user_id               ON public.skills      USING btree (user_id);
CREATE INDEX idx_skills_user_type             ON public.skills      USING btree (user_id, type);

CREATE INDEX idx_users_active                 ON public.users       USING btree (id) WHERE (is_active = true);
CREATE INDEX idx_users_email                  ON public.users       USING btree (email);
CREATE INDEX idx_users_portfolio_name_active  ON public.users       USING btree (portfolio_name) WHERE (is_active = true);

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.reorder_courses_for_user(target_user_id integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM courses
        WHERE user_id = target_user_id
    )
    UPDATE courses
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE courses.id = reordered.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_education_for_user(target_user_id integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM education
        WHERE user_id = target_user_id
    )
    UPDATE education
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE education.id = reordered.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_projects_for_user(target_user_id integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    WITH reordered AS (
        SELECT id,
            ROW_NUMBER() OVER (
                ORDER BY sort_order ASC, id DESC
            ) AS new_rank
        FROM projects
        WHERE user_id = target_user_id
    )
    UPDATE projects
    SET sort_order = reordered.new_rank
    FROM reordered
    WHERE projects.id = reordered.id;
END;
$function$;

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- NOTE: project_categories currently has RLS DISABLED (fully exposed to anon
-- and authenticated roles). Enable it manually with a real policy set — do
-- not blindly enable it here, as that would block all access until policies
-- exist. To enable once you've decided on policies:
--   ALTER TABLE public.project_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_codes       ENABLE ROW LEVEL SECURITY;

-- ----- users -----
CREATE POLICY "Allow public delete"       ON public.users FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for everyone" ON public.users FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for everyone" ON public.users FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for everyone" ON public.users FOR UPDATE TO public USING (true);
CREATE POLICY "Public View Users"          ON public.users FOR SELECT TO public USING (true);

-- ----- experiences -----
CREATE POLICY "Allow public delete"            ON public.experiences FOR DELETE TO public USING (true);
CREATE POLICY "Enable delete for experiences"  ON public.experiences FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for experiences"  ON public.experiences FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for experiences"  ON public.experiences FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for experiences"  ON public.experiences FOR UPDATE TO public USING (true);
CREATE POLICY "Public View Experiences"        ON public.experiences FOR SELECT TO public USING (true);

-- ----- skills -----
CREATE POLICY "Allow public delete"       ON public.skills FOR DELETE TO public USING (true);
CREATE POLICY "Enable delete for skills"  ON public.skills FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for skills"  ON public.skills FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for skills"  ON public.skills FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for skills"  ON public.skills FOR UPDATE TO public USING (true);
CREATE POLICY "Public View Skills"        ON public.skills FOR SELECT TO public USING (true);

-- ----- projects -----
CREATE POLICY "Allow public delete"         ON public.projects FOR DELETE TO public USING (true);
CREATE POLICY "Enable delete for projects"  ON public.projects FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for projects"  ON public.projects FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for projects"  ON public.projects FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for projects"  ON public.projects FOR UPDATE TO public USING (true);
CREATE POLICY "Public View Projects"        ON public.projects FOR SELECT TO public USING (true);

-- ----- education -----
CREATE POLICY "Enable delete for education"  ON public.education FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for education"  ON public.education FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for education"  ON public.education FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for education"  ON public.education FOR UPDATE TO public USING (true);

-- ----- courses -----
CREATE POLICY "Enable delete for courses"  ON public.courses FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for courses"  ON public.courses FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for courses"  ON public.courses FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for courses"  ON public.courses FOR UPDATE TO public USING (true);

-- ----- auth_codes -----
CREATE POLICY "Allow public delete"            ON public.auth_codes FOR DELETE TO public USING (true);
CREATE POLICY "Enable delete for secret_key"   ON public.auth_codes FOR DELETE TO public USING (true);
CREATE POLICY "Enable insert for secret_key"   ON public.auth_codes FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable select for secret_key"   ON public.auth_codes FOR SELECT TO public USING (true);
CREATE POLICY "Enable update for secret_key"   ON public.auth_codes FOR UPDATE TO public USING (true);

COMMIT;

-- ============================================================
-- Notes for migration to another Postgres provider:
-- 1. No triggers exist in this schema (verified).
-- 2. IDs use GENERATED BY DEFAULT AS IDENTITY instead of Supabase's
--    serial + sequence naming (e.g. secret_key_id_seq) for portability.
--    If you need to preserve exact sequence names/values, adjust accordingly.
-- 3. This schema does NOT include Supabase-specific features:
--    RLS policies, auth schema, storage buckets, or realtime config.
--    Check separately if your app relies on Supabase Auth/Storage/RLS -
--    these will need reimplementation on the new provider.
-- 4. No extensions (e.g. pgcrypto, uuid-ossp) were in use.
-- ============================================================

-- ============================================================
-- Seed Data (Temporary Placeholder Profile)
-- ============================================================

-- Insert a temporary active user
INSERT INTO public.users (
  name, 
  job_title, 
  email, 
  hero_description, 
  about_description, 
  capabilities_description, 
  about_title, 
  linkedin_url, 
  github_url, 
  resume_url, 
  portfolio_name, 
  is_active
) VALUES (
  'Zaid Radaideh', 
  'Software Engineer', 
  'zaidradaideh.dev@gmail.com', 
  'Building beautiful, robust, and scalable web applications.', 
  'I am a passionate software engineer dedicated to crafting seamless digital experiences and solving complex problems.', 
  'My core capabilities include full-stack web development, system design, and ensuring high-quality software delivery.', 
  'About Me', 
  'https://linkedin.com/in/zaid-radaideh', 
  'https://github.com/zaid-radaideh', 
  'https://zaid-alradaideh.vercel.app/resume.pdf', 
  'Zaid''s Portfolio', 
  true
);

-- Note: We use DO block or subqueries to get the user_id dynamically for the related tables.
DO $$
DECLARE
  v_user_id int;
BEGIN
  SELECT id INTO v_user_id FROM public.users WHERE email = 'zaidradaideh.dev@gmail.com' LIMIT 1;

  -- Insert Project
  INSERT INTO public.projects (
    user_id, title, client, role, year, status, sort_order, description, technologies, live_url
  ) VALUES (
    v_user_id, 
    'Portfolio Website — Personal project', 
    'Personal', 
    'Full-stack developer', 
    2026, 
    'Completed', 
    1, 
    'A personal portfolio to showcase my projects, skills, and experiences. Built with modern web technologies.', 
    'Next.js/TS, React/TS, Tailwind CSS, Node.js', 
    'https://zaid-alradaideh.vercel.app'
  );

  -- Insert Skill
  INSERT INTO public.skills (
    user_id, name, type
  ) VALUES (
    v_user_id, 
    'React', 
    'primary'
  );

  -- Insert Experience
  INSERT INTO public.experiences (
    user_id, role, company, period, description
  ) VALUES (
    v_user_id, 
    'Internship — Quality Assurance', 
    'ARD (ArabiaWeather)', 
    'Sep 2025 – Present', 
    'Assisted in the quality assurance process, testing software to ensure it meets standard requirements and specifications.'
  );

  -- Insert Course
  INSERT INTO public.courses (
    user_id, title, provider, year, type, hours
  ) VALUES (
    v_user_id, 
    'AWS Certified Cloud Practitioner', 
    'AWS', 
    2026, 
    'certificate', 
    12
  );

  -- Insert Education
  INSERT INTO public.education (
    user_id, institution, degree, period, sort_order
  ) VALUES (
    v_user_id, 
    'Jordan University of Science and Technology', 
    'Bachelor of Software Engineering', 
    '2021–2025', 
    1
  );

END $$;
